### ISSUE TITLE
Add English Version To The ReadMe file [将英语版本添加到自述文件]

### ISSUE THREAD

**Issue by anje123** [chaosblade-io/chaosblade-help-doc#13]
This should be implemented to make it easy for those who understand English not Chinese find the Readme File easy and fast to understand
应当实施此程序，以使那些懂英语而不是中文的人更容易快速地找到自述文件。

**Comment by anje123** [comment]
issue to me

**Comment by xcaspar** [comment]
@anje123 Thank you for your contribution.
